agent_name = "twilio-agent-henk1"
image = "docker.io/tristanvandoorn1/twilio-agent-henk1:0.7"
# image_credentials = "dockerhub-access"  # Optioneel: gebruik bij private registry
secret_set = "openai-twilio-secrets"

[scaling]
min_agents = 0
